import { Router } from "express";
import authRouter from "./auth.js";
import tasksRouter from "./tasks.js";
import usersRouter from "./users.js";
import settingsRouter from "./settings.js";
import notificationsRouter from "./notifications.js";
import feedRouter from "./feed.js";
import dmRouter from "./dm.js";
import clientsRouter from "./clients.js";
import pokeRouter from "./poke.js";
import searchRouter from "./search.js";
import dutyRouter from "./duty.js";
import dutyEmailRouter from "./duty-email.js";
import pushRouter from "./push.js";
import taskFilesRouter from "./task-files.js";
import taskReviewRouter from "./task-review.js";
import reviewCommentsRouter from "./review-comments.js";
import escalaRouter from "./escala.js";
import monitorRouter from "./monitor.js";
import replanoRouter from "./replano.js";
import fluxoRouter from "./fluxo.js";
import contestationsRouter from "./contestations.js";

const router = Router();
router.use(authRouter);
router.use(tasksRouter);
router.use(usersRouter);
router.use(settingsRouter);
router.use(notificationsRouter);
router.use(feedRouter);
router.use(dmRouter);
router.use(clientsRouter);
router.use(pokeRouter);
router.use(searchRouter);
router.use(dutyEmailRouter);
router.use(dutyRouter);
router.use(pushRouter);
router.use(taskFilesRouter);
router.use(taskReviewRouter);
router.use(reviewCommentsRouter);
router.use(escalaRouter);
router.use(monitorRouter);
router.use(replanoRouter);
router.use(fluxoRouter);
router.use(contestationsRouter);

export default router;
